import java.io.PrintWriter

import sbt.{File, taskKey}

/**
  * Automatically generate some code during "sbt compile"
  * @author robert xue
  * @since 12/26/17.
  */
object CodeGenTokenSyntax {
  final val generateCode = taskKey[Seq[File]]("Generate boilerplate code for niffler core.")
  def saveToFile(srcFolder: File): File = {
    srcFolder.mkdirs()
    val file = new File(srcFolder, "com/roboxue/niffler/syntax/TokenSyntax.scala")
    file.getParentFile.mkdirs()
    val writer = new PrintWriter(file)
    try {
      // Function types with 23 arity aren't supported by scala
      writer.println("// auto generated by sbt compile")
      file
    } finally {
      writer.close()
    }
  }
}