package com.roboxue.niffler

/**
  * @author robert.xue
  * @since 7/15/18
  */
trait Requirement {
  val dependsOn: Seq[TokenMeta]
}

object Requirement0 extends Requirement {
  override val dependsOn: Seq[TokenMeta] = Seq.empty

  def ~>[Out](outlet: Token[Out]): Formula0[Out] = outputTo(outlet)

  def outputTo[Out](outlet: Token[Out]): Formula0[Out] = Formula0(outlet)
}

// The other stuff will be auto generated by sbt
